### PR TITLE
Detect selectionchange on compositionupdate instead

### PR DESCRIPTION
**Pull request by fraziermork**
On every compositionupdate, we compare the computed compositionRange to a SelectionState we compute from the DOM selection. If the current selection isn't within the compositionRange, the user moved the selection, so we need to fake a compositionend for the word they were composing and reset for the new word under composition.:

*Before* submitting a pull request, please make sure the following is done...

1. Fork the repo and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure that:
  * The test suite passes (`npm test`)
  * Your code lints (`npm run lint`) and passes Flow (`npm run flow`)
  * You have followed the [testing guidelines](https://github.com/facebook/draft-js/wiki/Testing-for-Pull-Requests)
5. If you haven't already, complete the [CLA](https://code.facebook.com/cla).

Please use the simple form below as a guideline for describing your pull request.

Thanks for contributing to Draft.js!

-

**Summary**

[...]

**Test Plan**

[...]

### CODE REVIEW

**Comment by adamsanderson** [comment]
Looks like linting is failing. I'll at the logic later tonight.

**Comment by fraziermork** [comment]
I'm bummed cause @johnrjj no longer autocompletes or shows up as an option for a reviewer 
Pln9qRt

**Comment by johnrjj** [comment]
all-seeing-john

**Review by adamsanderson — APPROVED** [review]
Looks good.
I'm curious how this works when the update is something like:

cat => cats, do we know that the new composition range is 4 characters instead of 3 for the purposes of detecting the change?

**Comment by fraziermork** [comment]
@adamsanderson It's complicated to explain, so here are some logs from typing `The ` instead:

`|`: caret on an empty line

`T|`: 
Screen Shot 2019-11-08 at 3 11 04 PM

`Th|`: 
Screen Shot 2019-11-08 at 3 11 22 PM

`The|`: 
Screen Shot 2019-11-08 at 3 11 38 PM

`The |`: 
Screen Shot 2019-11-08 at 3 12 13 PM

You know what the compositionRange is. The draft selection from DOM is the result of `deriveSelectionFromDOM/getDraftEditorSelection`. The "actual DOM selection" is what I get from this code: 
```javascript
const sel = window.getSelection();
console.log(`actual DOM selection`, { anchorOffset: sel.anchorOffset, focusOffset: sel.focusOffset });
```

My working understanding is that the window selection is uncollapsed at the time of `compositionupdate`, then a `selectionchange` immediately fires that sets it back to a caret at the end (there is no `selectionchange` event to uncollapse the selection because IME I guess). Since we're doing this comparison during the `compositionupdate` handler, we can see the ephemeral, expanded selection before `selectionchange` collapses it to the end again.

**Comment by adamsanderson** [comment]
1. Awesome description, thank you @fraziermork!
2. Greetings SauronJohn (aka @johnrjj)
3. So it looks like `beforeInput` won't have the right selection (that makes sense, nothing has happened) but after that a `select` event has the right range… I'm wondering if hooking plain input events for insertCompositionText gives us the proper ranges.  That might be more reliable.

**Pull request merged**
