### PR TITLE
Only update content when forcing refresh

### PR DESCRIPTION
**Pull request by max-winderbaum**
Fixes https://github.com/textioHQ/editor/issues/618

### CODE REVIEW

**Comment by max-winderbaum** [comment]
The issue is we are reaching down from `frontend` and manipulating the CSS styles of the `contenteditable` div. When we force refresh of the whole div we blow away those styles, which causes the jitter. We can get around this by only forcing a refresh on the draft content itself, which lives under the `contenteditable` div.

**Comment by colinjeanne** [comment]
Why is the frontend manipulating styles of a component it doesn't own? That sounds like the root cause here.

**Comment by max-winderbaum** [comment]
I'll investigate this more tomorrow - I had that thought and the answer deserves to be tracked down.

**Comment by max-winderbaum** [comment]
This key is on DraftEditorContents because we need to modify the CE div's inline styles to add padding on either side. We need this padding to be on either side of the CE div in order to have a click translate into an appropriate selection in draft. Because the padding is dynamically calculated as the window resizes we can't put it in a class; it has to be an inline style. When the key is on the root element, changing it rerenders the CE div and blows away our padding styles, which causes a jitter in IE. Putting the key here is sufficient to rerender the contents of the editor.

@see https://github.com/textioHQ/editor/issues/618
@see https://github.com/textioHQ/frontend/blob/d70af8a570163d7b3b3012712f58a4257c5b7282/app/es/helpers/borderManager.js#L111-L111
@see https://github.com/textioHQ/frontend/blob/e456e374f5edcbad7bb11952b542190b52220093/app/es/components/editor/content.js#L98-L98

**Comment by max-winderbaum** [comment]
@colinjeanne says :ship:

**Pull request merged**
